[package]
name = "illusionna"
version = "0.1.0"
edition = "2021"

[dependencies]
http = "1.1.0"
iced = "0.12.1"
octocrab = "0.38.0"
serde_json = "1.0.121"
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
