name: Release on Tag

on:
  push:
    tags:
      - "*"

jobs:
  release:
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact_name: ${{ github.event.repository.name }}.exe
            asset_name: ${{ github.event.repository.name }}-windows.exe
          - os: macos-latest
            artifact_name: ${{ github.event.repository.name }}
            asset_name: ${{ github.event.repository.name }}-macos
          - os: ubuntu-latest
            artifact_name: ${{ github.event.repository.name }}
            asset_name: ${{ github.event.repository.name }}-linux
    runs-on: ${{ matrix.os }}
    env:
      ILLUSIONNA_GITHUB_APP: ILLUSIONNA_GITHUB_APP=${{ secrets.ILLUSIONNA_GITHUB_APP }}
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release
      - name: Upload
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.REPOSITORY_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}