name: Release on Tag

on:
  push:
    tags:
      - "*"

jobs:
  release:
    strategy:
      matrix:
        include:
          - runner: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: ${{ github.event.repository.name }}.exe
            asset_name: ${{ github.event.repository.name }}-windows.exe
          - runner: macos-latest
            target: x86_64-apple-darwin
            artifact_name: ${{ github.event.repository.name }}
            asset_name: ${{ github.event.repository.name }}-macos
          - runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: ${{ github.event.repository.name }}
            asset_name: ${{ github.event.repository.name }}-linux
    runs-on: ${{ matrix.runner }}
    env:
      ILLUSIONNA_GITHUB_APP: ${{ secrets.ILLUSIONNA_GITHUB_APP }}
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          rustup target add ${{ matrix.target }}
          cargo build --release --target ${{ matrix.target }}
      - name: Upload
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.REPOSITORY_TOKEN }}
          file: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}